services:

  mysql:
    image: mysql:8.0
    container_name: online-banking-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onlinebanking2

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile.devops

    container_name: online-banking-app

    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root

    ports:
      - "8080:8080"

    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data: